# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.3"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - couchdb:1.6.1

# Cache gems in between builds
cache:
  paths:
    - vendor/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v
  - curl -s couchdb:5984
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec ruby /builds/leap/nickserver/bin/nickserver version
  - apt update -y
  - apt install -y lsof

test:
  script:
  - TEST_OPTS=-v bundle exec rake test
